### ISSUE TITLE
添加资产报错

### ISSUE THREAD

**Issue by Maysec** [adysec/ARL#1]
<img width="1339" alt="image" src="https://github.com/adysec/ARL/assets/53160265/a25c96bb-ef6e-46ce-addb-435ffe85630a">

**Comment by adysec** [comment]
有web界面的截图么，或者weblog文件

**Comment by adysec** [comment]
了解了，你这边应该是直接拉的docker运行的，我这边调试的是docker内源码安装的方式
docker上传镜像时不保存硬编码密码，已更新readme文档，拉取docker后，进入docker内重设rabbitmq密码即可

**Comment by ZhongLiuShi** [comment]
> 了解了，你这边应该是直接拉的docker运行的，我这边调试的是docker内源码安装的方式 docker上传镜像时不保存硬编码密码，已更新readme文档，拉取docker后，进入docker内重设rabbitmq密码即可

还是会有报错，麻了
