### ISSUE TITLE
指纹数据及处理脚本存在问题

### ISSUE THREAD

**Issue by s1g0day** [adysec/ARL#10]
在指纹数据中存在类似多行的数据

![image](https://github.com/user-attachments/assets/b7e25860-9a07-4297-82b0-d0dbff5451a9)

使用提供的代码发现并未处理此类情况

![image](https://github.com/user-attachments/assets/6d2db7f7-3c08-4f8a-979e-dec9d58224b7)

提供一种解决方案，改变指纹数据文件格式及处理代码

![image](https://github.com/user-attachments/assets/2b3326c3-77fa-42f8-b4cf-36cca8b4111c)

```
import yaml

def finger_update_data():

    # 加载配置
    push_config = yaml.safe_load(open("config/finger_arl.yaml", "r", encoding="utf-8").read())

    for i in range(len(push_config['finger_arl'])):
        print(push_config['finger_arl'][i]['name'], push_config['finger_arl'][i]['rule'])

    print("共检测到", len(push_config['finger_arl']), "个指纹")

finger_update_data()
```
或者在生成指纹数据时，处理好格式

---
补充，这种方式在处理多个引号时，会将其转义为1个，但对name属性来说应该不重要

![image](https://github.com/user-attachments/assets/34a3b5ab-b9c0-4352-9d63-b27504f6bcf5)

**Comment by adysec** [comment]
非常感谢，已按照您提供的加载配置的方式，修改读取yaml文件相关代码
