### ISSUE TITLE
师傅 docker源码安装问题

### ISSUE THREAD

**Issue by JackeyLov5** [adysec/ARL#11]
config/finger_arl.yaml 
<img width="790" alt="image" src="https://github.com/user-attachments/assets/f24fd3e4-ca5e-4554-ac88-520d02e2405f">
安装时报了个这个错 不太了解docker怎么解决呢
这个配置文件是在docker哪里？还是在vps呢
thx

**Comment by adysec** [comment]
这个是因为https://github.com/adysec/ARL/issues/10中提到的有少量指纹导入失败的问题，修改了相关代码，但是文件名没改过来，已更新tools/add_finger.py文件，对应读取tools/finger_arl.yaml指纹文件

**Comment by JackeyLov5** [comment]
或者有添加指纹而不重复的方法吗

**Comment by adysec** [comment]
已添加`ehole_magic`指纹，附指纹文件`https://github.com/adysec/ARL/blob/master/tools/finger.json`、添加脚本`https://github.com/adysec/ARL/blob/master/tools/add_finger_ehole.py`

**Comment by JackeyLov5** [comment]
> 已添加`ehole_magic`指纹，附指纹文件`https://github.com/adysec/ARL/blob/master/tools/finger.json`、添加脚本`https://github.com/adysec/ARL/blob/master/tools/add_finger_ehole.py`

师傅 这个需要手动去运行脚本吗。还是说发布的已经是合并去重的orz
