### ISSUE TITLE
师傅，指纹添加问题

### ISSUE THREAD

**Issue by YingxueSec** [adysec/ARL#12]
师傅你好，
我采用的 docker 部署方式1
这个json 文件只有 5000 多指纹。请问一下 md 介绍中的 2w 多指纹如何添加呢？
谢谢师傅
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/4f7832c5-e5ca-4257-be2e-1fc13ff5cc06">

添加指纹后还是只有 5000多条。
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/9b54510d-d7d9-45fd-9ac9-01f02d9f7b73">

**Comment by YingxueSec** [comment]
我看仓库的是有 2w 多的指纹 json。是替换一下吗？

**Comment by YingxueSec** [comment]
尝试替换后，加载失败
<img width="798" alt="image" src="https://github.com/user-attachments/assets/87069cf6-6886-4e3f-8697-ec34c4d673dc">

**Comment by YingxueSec** [comment]
<img width="1691" alt="image" src="https://github.com/user-attachments/assets/7f09cca1-f82d-4735-8e7e-d4b199ac1079">

**Comment by adysec** [comment]
docker直接启动的只有5k多，readme中的2w是需要另外运行一下add_finger_ehole.py脚本的



---原始邮件---
发件人: "Ying ***@***.***&gt;
发送时间: 2024年7月19日(周五) 上午10:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [adysec/ARL] 师傅，指纹添加问题 (Issue #12)




 image.png (view on web)

**Comment by YingxueSec** [comment]
谢谢师傅，解决了，
请问一下师傅了解任务长期处于file_leak状态，是文件字典哪个特殊符号影响的吗？我自己替换了字典就一直处于这个状态了。

**Comment by adysec** [comment]
可能是，也可能是字典太大了导致的
