### ISSUE TITLE
灯塔一键安装脚本无法运行

### ISSUE THREAD

**Issue by 2477231995** [adysec/ARL#13]
我用的centos7
这个shell脚本跑不起来，删除前面空行也不行，报错语法在前括号那，变成单引号更不行了
![1](https://github.com/user-attachments/assets/c89b07c4-768c-4fba-83e1-bdca7da3adf5)

![2](https://github.com/user-attachments/assets/0b69fbc5-dadb-481c-a582-31c9b6d39d03)

**Comment by adysec** [comment]
你获取到的脚本不对，这个只是html页面，可以用浏览器看一下正确的脚本是什么样的

**Comment by 2477231995** [comment]
OK，是我那两台机器的问题，用云服务器wget就能下载了

**Comment by 2477231995** [comment]
采用这个源码安装shell脚本执行过后文件夹在哪落地呢佬，我看了下opt目录下啥也没有
![image](https://github.com/user-attachments/assets/4682504d-e473-484b-9a7c-443267fe7b8d)

**Comment by adysec** [comment]
说明还是操作不对，如果不会用安装脚本的话，建议使用docker打包好的镜像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月20日(周六) 下午3:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [adysec/ARL] 灯塔一键安装脚本无法运行 (Issue #13)




 
采用这个源码安装shell脚本执行过后文件夹在哪落地呢佬，我看了下opt目录下啥也没有
 image.png (view on web)

**Comment by 2477231995** [comment]
我用这个docker内安装了，
![QQ_1721465949190](https://github.com/user-attachments/assets/ba9888c2-13ac-4141-9ac8-ef4cac2fd160)
存在镜像bin并且都在运行，但是我通过ip:5003访问没响应，接下来咋办
![QQ_1721466053427](https://github.com/user-attachments/assets/8a87412a-a436-434f-b024-4624cc9311f4)

**Comment by 2477231995** [comment]
这个页面大佬
![QQ_1721466201006](https://github.com/user-attachments/assets/ef658df5-3f57-4963-ac59-b5b02a0d9840)

**Comment by 2477231995** [comment]
师傅看到指导我一下，之前部署原班那个两天花了很久都没成功

**Comment by adysec** [comment]
docker使用及网络问题，请自行百度学习解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月20日(周六) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [adysec/ARL] 灯塔一键安装脚本无法运行 (Issue #13)




 
师傅看到指导我一下，之前部署原班那个两天花了很久都没成功

**Comment by 2477231995** [comment]
他这个不出页面是不是web服务那没调好，网络应该是没问题的，就是起不来web



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月21日(周日) 凌晨5:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [adysec/ARL] 灯塔一键安装脚本无法运行 (Issue #13)




 docker使用及网络问题，请自行百度学习解决 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年7月20日(周六) 下午5:37 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [adysec/ARL] 灯塔一键安装脚本无法运行 (Issue #13) 
 
 
 
 
   
 师傅看到指导我一下，之前部署原班那个两天花了很久都没成功

**Comment by 2477231995** [comment]
好了大佬，感谢贡献！这个还需要我们自己配置测绘的api吗

**Comment by adysec** [comment]
参考arl原文档说明



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月21日(周日) 上午9:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [adysec/ARL] 灯塔一键安装脚本无法运行 (Issue #13)




 
好了大佬，感谢贡献！这个还需要我们自己配置测绘的api吗
