### ISSUE TITLE
未知原因导致timeout of 12000ms exceeded

### ISSUE THREAD

**Issue by superd1ng** [adysec/ARL#18]
按照docker 部署方式
![image](https://github.com/user-attachments/assets/994f9bbd-740f-46c5-8343-2f0d5c982216)
出现如下错误
![image](https://github.com/user-attachments/assets/2884e1fd-1223-4c50-81e1-962c7913492f)
![image](https://github.com/user-attachments/assets/9b1ab708-1155-4580-be4d-086872c9c08c)

**Comment by adysec** [comment]
由于启动服务和数据库需要时间（几秒钟），docker安装部署的命令需要逐行复制，每行命令间隔几秒
