### ISSUE TITLE
docker内源码安装永远都有这个问题。。

### ISSUE THREAD

**Issue by JackeyLov5** [adysec/ARL#19]
start services ...
Job for mongod.service failed because a timeout was exceeded.
See "systemctl status mongod.service" and "journalctl -xe" for details.

rt 查了很久一直没解决

**Comment by adysec** [comment]
docker内源码安装需要有良好的境外网络，且需要一定的服务器性能，建议使用docker部署的方式。如需要docker内源码安装，建议逐步执行bash安装脚本的内容

**Comment by risuxx** [comment]
> start services ... Job for mongod.service failed because a timeout was exceeded. See "systemctl status mongod.service" and "journalctl -xe" for details.
> 
> rt 查了很久一直没解决

我也遇到了一样的问题，我尝试多次运行docker exec arl bash -c "bash misc/setup-arl.sh"似乎在第二次运行时不会出现该报错。

**Comment by adysec** [comment]
建议根据misc/setup-arl.sh中代码，复制出来逐步运行，不要直接运行bash脚本，因为启动服务需要有一定时间，对性能冗余要求较高
