### ISSUE TITLE
关于安装

### ISSUE THREAD

**Issue by dddwill8-day0** [adysec/ARL#2]
docker源码安装，服务均启动，但是无法进行扫描，一直是waiting
centos8.4源码安装，排错后成功启动，可以扫描
cetos7.6 && centos7.9 均无法正常安装，望周知

**Comment by adysec** [comment]
1.docker内源码安装：需要能够正常访问github，需要下载工具，建议使用国外服务器，如网络较差或使用国内服务器，老老实实用docker启动就行了
2.centos版本问题：centos8可以安装，centos7无法正常安装，原因为centos7镜像不存在systemd服务，因此仅能在centos8环境中使用，在readme文档中有说明（第一条就是）

**Comment by adysec** [comment]
1.docker内源码安装：需要能够正常访问github，需要下载工具，建议使用国外服务器，如网络较差或使用国内服务器，老老实实用docker启动就行了
2.centos版本问题：centos8可以安装，centos7无法正常安装，原因为centos7镜像不存在systemd服务，因此仅能在centos8环境中使用，在readme文档中有说明（第一条就是）
