### ISSUE TITLE
跑监控任务过一段时间会自动停下

### ISSUE THREAD

**Issue by Pooppoka** [adysec/ARL#21]
跑监控任务过一段时间会自动停下，也没有报错信息，各个服务都是正常运行，选择的是docker内源码安装，资产监控运行次数为0，跑不起来，任务并发调整为2也不行

**Comment by adysec** [comment]
目前建议直接使用docker安装的方式运行项目，由于centos的docker镜像源时常更新，导致安装步骤略有不同，因此docker内源码安装需要有一定的调试能力，无法产出固定的参考配置文档

**Comment by Pooppoka** [comment]
原来如此 那我试试docker安装的

**Comment by Pooppoka** [comment]
我改用了直接拖取docker进行使用，没有其他修改配置的操作，发现问题依然存在，我是通过资产组下发监控任务，大概有110多个域名，一样是大概跑到了三十多个域名的时候就莫名其妙暂停了，余下的七十多个域名在web上面也不会显示正在运行，状态全部是done

虽然这时候灯塔已经不更新任务状态显示了，但是打开vps状态会一直运行celery的进程，看了一下日志好像worker.services有些报错，各个服务都运行正常，重装了几次都会出现一模一样的问题 ，如下图

![image](https://github.com/user-attachments/assets/11a67d5b-a4de-4004-b53b-8cd9351636a2)

![image](https://github.com/user-attachments/assets/7b7c9b22-cdfb-44f1-90fe-154af270f0e7)



这个问题已经持续一段时间了，一直在找原因也找不到，也尝试过修改并发任务数或其他操作，但是问题还是在，想请教一下是那个位置可能出现这个问题啊，该怎么解决呢

**Comment by adysec** [comment]
目测还是并发的问题，原版arl的arlgithub并发数量为1，arltask并发数量为3，另外，arl的监控任务本身写的就比较拉，建议直接通过首页去下发扫描任务，监控任务不适合大批量域名，也可以在宿主机上安装smartdns做负载均衡，docker内把dns地址指向vps宿主机地址
