### ISSUE TITLE
centos8.5安装过程mongod启动不了

### ISSUE THREAD

**Issue by gniuy** [adysec/ARL#3]
看前面的问题有人用centos8.4能正常安装，但是目前安装会自动更新到centos8.5后，脚本到了mongod这一步启动不了，有人遇到同样的问题吗

**Comment by adysec** [comment]
有详细一点的报错信息吗

**Comment by adysec** [comment]
看一下mongod.service文件吧，从报错上来看是启动mongodb时的权限问题，或者可以直接使用打包好的docker版本

**Comment by SQY1998** [comment]
> 看一下mongod.service文件吧，从报错上来看是启动mongodb时的权限问题，或者可以直接使用打包好的docker版本

我也是这个问题，请问这个需要什么命令启动特权呢

**Comment by adysec** [comment]
检查 PID 文件所有权：
    错误信息表明新的主 PID 不属于服务，并且 PID 文件不属于 root。这是关键，因为 systemd 期望 PID 文件属于 root，且服务进程与此文件中的 PID 匹配。

    检查配置文件：
    核实 MongoDB 配置文件（通常是 /etc/mongod.conf）是否设置正确，特别是 pidFilePath 指令。

    检查权限：
    确保必要的目录和文件具有正确的所有权和权限。

解决步骤

    验证 PID 文件所有权：
    检查 PID 文件（通常是 /var/run/mongodb/mongod.pid）的所有权。

ls -l /var/run/mongodb/mongod.pid

确保该文件属于 mongod:mongod。

chown mongod:mongod /var/run/mongodb/mongod.pid

检查 MongoDB 配置：
打开 MongoDB 配置文件并检查 pidFilePath 设置。

nano /etc/mongod.conf

确保设置正确，例如：

processManagement:
  pidFilePath: /var/run/mongodb/mongod.pid

检查目录权限：
确保 /var/run/mongodb 目录具有正确的所有权和权限。

chown -R mongod:mongod /var/run/mongodb
chmod 0755 /var/run/mongodb

重启 MongoDB 服务：
在进行必要的修正后，重启 MongoDB 服务。

systemctl restart mongod.service

检查服务状态：
验证 MongoDB 服务状态以确保其正常运行。

systemctl status mongod.service

**Comment by ca1ji** [comment]
我也遇到这个问题了

**Comment by adysec** [comment]
因为网络和服务器配置情况，建议逐步运行安装脚本`setup-arl.sh`，mongod服务因权限问题无法启动，在启动docker时使用`--privileged`参数，且因为docker镜像更新原因可能有变更，使用源码安装需要自行尝试版本
