### ISSUE TITLE
不知道为什么任务一多就会中断

### ISSUE THREAD

**Issue by zhifana** [adysec/ARL#7]
只要域名超过100个 不管是一次性任务还是资产监控就会运行一段时间后没有动静。
看了服务没有问题，docker日志也没有问题，arl日志会到最后运行完的域名结束就没有动静了

**Comment by WeaponA** [comment]
有找到问题吗？是不是namp 全端口扫描发包流量大导致的。

**Comment by zhifana** [comment]
不是 我端口设置是top100

**Comment by WeaponA** [comment]
我也遇到了两三次，停一段时间，过一段时间还会继续。我需要重启容器解决

**Comment by adysec** [comment]
性能问题，建议降低worker的并发数，/etc/systemd/system/arl-worker.service中修改-c参数即可，修改后需要使用systemctl restart arl-worker.service重启worker进程
